**Working on Claims severity :** Task is to create a better model and to find the predict the value for the 'loss' column. Variables prefaced with 'cat' are categorical, while those prefaced with 'cont' are continuous.Means must *predict the loss value for the ids in this file.*


For download the dataset click on the below link :
[link text](https://www.kaggle.com/c/allstate-claims-severity/data)

(By Jagannadan Manasa), Now i am trying to solve these Claims severity using a model.

In [227]:
import os
if 'COLAB_TPU_ADDR' not in os.environ: 
  print('Not connected to TPU') 
else: 
  print("Connected to TPU")

Not connected to TPU


In [1]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [2]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv


In [0]:
!unzip allstate-claims-severity.zip

Archive:  allstate-claims-severity.zip
replace allstate-claims-severity/sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: allstate-claims-severity/sample_submission.csv  
  inflating: allstate-claims-severity/sample_submission.csv.zip  
  inflating: allstate-claims-severity/test.csv  
  inflating: allstate-claims-severity/test.csv.zip  
  inflating: allstate-claims-severity/train.csv  
  inflating: allstate-claims-severity/train.csv.zip  


In [222]:
import pandas as pd
import io
import warnings
warnings.filterwarnings('ignore')
#data_train = pd.read_csv("allstate-claims-severity/train.csv", delimiter=',')
data_train = pd.read_csv("train.csv", delimiter=',')
#for fn in uploaded.keys():
#  print('User uploaded file "{name}" with length {length} bytes'.format(
#      name=fn, length=len(uploaded[fn])))

In [223]:
#data_test = pd.read_csv("allstate-claims-severity/test.csv", delimiter=',')
data_test = pd.read_csv("test.csv", delimiter=',')
#for fn in uploaded.keys():
#  print('User uploaded file "{name}" with length {length} bytes'.format(
#      name=fn, length=len(uploaded[fn])))

In [224]:
print("Train data dimensions: ", data_train.shape)
print("Test data dimensions: ", data_test.shape)

Train data dimensions:  (188318, 132)
Test data dimensions:  (125546, 131)


In [225]:
data_train.head()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont6     cont7  \
0   1    A    B    A    B    A    A    A    A    B  ...  0.718367  0.335060   
1   2    A    B    A    A    A    A    A    A    B  ...  0.438917  0.436585   
2   5    A    B    A    A    B    A    A    A    B  ...  0.289648  0.315545   
3  10    B    B    A    B    A    A    A    A    B  ...  0.440945  0.391128   
4  11    A    B    A    B    A    A    A    A    B  ...  0.178193  0.247408   

     cont8    cont9   cont10    cont11    cont12    cont13    cont14     loss  
0  0.30260  0.67135  0.83510  0.569745  0.594646  0.822493  0.714843  2213.18  
1  0.60087  0.35127  0.43919  0.338312  0.366307  0.611431  0.304496  1283.60  
2  0.27320  0.26076  0.32446  0.381398  0.373424  0.195709  0.774425  3005.09  
3  0.31796  0.32128  0.44467  0.327915  0.321570  0.605077  0.602642   939.85  
4  0.24564  0.22089  0.21230  0.204687  0.202213  0.246011  0.432606  2763.85  

[5 rows x 132 columns]

In [226]:
print('Number of missing values', data_train.isnull().sum().sum())

Number of missing values 0


For better understanding let us explore the data into stastical process

In [227]:
data_train.describe()

id          cont1          cont2          cont3  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean   294135.982561       0.493861       0.507188       0.498918   
std    169336.084867       0.187640       0.207202       0.202105   
min         1.000000       0.000016       0.001149       0.002634   
25%    147748.250000       0.346090       0.358319       0.336963   
50%    294539.500000       0.475784       0.555782       0.527991   
75%    440680.500000       0.623912       0.681761       0.634224   
max    587633.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.491812       0.487428       0.490945       0.484970   
std         0.211292       0.209027       0.205273       0.178450   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.336105       0.350175   
50%         0.452887       0.422268       0.440945       0.438285   
75%         0.652072       0.643315       0.655021       0.591045   
max         0.954297       0.983674       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.486437       0.485506       0.498066       0.493511   
std         0.199370       0.181660       0.185877       0.209737   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.312800       0.358970       0.364580       0.310961   
50%         0.441060       0.441450       0.461190       0.457203   
75%         0.623580       0.566820       0.614590       0.678924   
max         0.980200       0.995400       0.994980       0.998742   

              cont12         cont13         cont14           loss  
count  188318.000000  188318.000000  188318.000000  188318.000000  
mean        0.493150       0.493138       0.495717    3037.337686  
std         0.209427       0.212777       0.222488    2904.086186  
min         0.036232       0.000228       0.179722       0.670000  
25%         0.311661       0.315758       0.294610    1204.460000  
50%         0.462286       0.363547       0.407403    2115.570000  
75%         0.675759       0.689974       0.724623    3864.045000  
max         0.998484       0.988494       0.844848  121012.250000

In [228]:
data_train.columns

Index(['id', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8',
       'cat9',
       ...
       'cont6', 'cont7', 'cont8', 'cont9', 'cont10', 'cont11', 'cont12',
       'cont13', 'cont14', 'loss'],
      dtype='object', length=132)

In [229]:
data_test.head()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont5     cont6  \
0   4    A    B    A    A    A    A    A    A    B  ...  0.281143  0.466591   
1   6    A    B    A    B    A    A    A    A    B  ...  0.836443  0.482425   
2   9    A    B    A    B    B    A    B    A    B  ...  0.718531  0.212308   
3  12    A    A    A    A    B    A    A    A    A  ...  0.397069  0.369930   
4  15    B    A    A    A    A    B    A    A    A  ...  0.302678  0.398862   

      cont7    cont8    cont9   cont10    cont11    cont12    cont13    cont14  
0  0.317681  0.61229  0.34365  0.38016  0.377724  0.369858  0.704052  0.392562  
1  0.443760  0.71330  0.51890  0.60401  0.689039  0.675759  0.453468  0.208045  
2  0.325779  0.29758  0.34365  0.30529  0.245410  0.241676  0.258586  0.297232  
3  0.342355  0.40028  0.33237  0.31480  0.348867  0.341872  0.592264  0.555955  
4  0.391833  0.23688  0.43731  0.50556  0.359572  0.352251  0.301535  0.825823  

[5 rows x 131 columns]

In [230]:
print('Number of missing values', data_test.isnull().sum().sum())

Number of missing values 0


In [231]:
data_test.describe()

id          cont1          cont2          cont3  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean   294067.153442       0.494447       0.506939       0.498255   
std    170098.335649       0.187961       0.206837       0.201746   
min         4.000000       0.000016       0.001149       0.002634   
25%    146414.250000       0.347403       0.358319       0.336963   
50%    294306.000000       0.475784       0.555782       0.527991   
75%    441800.000000       0.626630       0.681761       0.634224   
max    587634.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean        0.492334       0.487640       0.492188       0.485945   
std         0.210815       0.209119       0.205574       0.178650   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.336105       0.352087   
50%         0.452887       0.422268       0.441525       0.438893   
75%         0.652072       0.643315       0.659261       0.591284   
max         0.956046       0.983107       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  125546.000000  125546.000000  125546.000000  125546.000000   
mean        0.487401       0.486015       0.498909       0.494360   
std         0.199549       0.182134       0.185950       0.210399   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.317960       0.358970       0.364580       0.310961   
50%         0.441060       0.441450       0.466720       0.457203   
75%         0.629180       0.568890       0.619840       0.678924   
max         0.982800       0.995400       0.994980       0.997830   

              cont12         cont13         cont14  
count  125546.000000  125546.000000  125546.000000  
mean        0.494033       0.495086       0.495586  
std         0.210148       0.213108       0.222613  
min         0.036232       0.000228       0.178568  
25%         0.318249       0.315758       0.294752  
50%         0.462286       0.363547       0.406104  
75%         0.682413       0.689974       0.724791  
max         0.997416       0.988494       0.844814

In [232]:
data_test.columns

Index(['id', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8',
       'cat9',
       ...
       'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10', 'cont11',
       'cont12', 'cont13', 'cont14'],
      dtype='object', length=131)

In [233]:
ID = data_test['id']
data_test.drop('id',axis=1,inplace=True)
#displaying first five rows
print(data_train.head(5))
%matplotlib inline
print(data_train.skew())

   id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont6     cont7  \
0   1    A    B    A    B    A    A    A    A    B  ...  0.718367  0.335060   
1   2    A    B    A    A    A    A    A    A    B  ...  0.438917  0.436585   
2   5    A    B    A    A    B    A    A    A    B  ...  0.289648  0.315545   
3  10    B    B    A    B    A    A    A    A    B  ...  0.440945  0.391128   
4  11    A    B    A    B    A    A    A    A    B  ...  0.178193  0.247408   

     cont8    cont9   cont10    cont11    cont12    cont13    cont14     loss  
0  0.30260  0.67135  0.83510  0.569745  0.594646  0.822493  0.714843  2213.18  
1  0.60087  0.35127  0.43919  0.338312  0.366307  0.611431  0.304496  1283.60  
2  0.27320  0.26076  0.32446  0.381398  0.373424  0.195709  0.774425  3005.09  
3  0.31796  0.32128  0.44467  0.327915  0.321570  0.605077  0.602642   939.85  
4  0.24564  0.22089  0.21230  0.204687  0.202213  0.246011  0.432606  2763.85  

[5 rows x 132 columns]
id       -0.002155
co

In [234]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188318 entries, 0 to 188317
Columns: 132 entries, id to loss
dtypes: float64(15), int64(1), object(116)
memory usage: 189.7+ MB


In [235]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125546 entries, 0 to 125545
Columns: 130 entries, cat1 to cont14
dtypes: float64(14), object(116)
memory usage: 124.5+ MB


Count how many colums are there in the train csv file and test cvs file?

In [236]:
cont_Featureslist1 = []
for colName,x in data_test.iloc[1,:].iteritems():
    #print(x)
    if(not str(x).isalpha()):
        cont_Featureslist1.append(colName)

print(cont_Featureslist1)

['cont1', 'cont2', 'cont3', 'cont4', 'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10', 'cont11', 'cont12', 'cont13', 'cont14']


In [237]:
Count = sum(str(x).isalpha() for x in data_train.iloc[1,:])
print("Number of categories: ",Count)

Number of categories:  116


There are many types of models developed to impliment  Claims severity.
There are :


1.   Linear Regression (Linear algo) 
2.   Ridge Regression (Linear algo)
3.   LASSO Linear Regression (Linear algo)
4.   Elastic Net Regression (Linear algo)
5.   KNN (non-linear algo)
6.   CART (non-linear algo)
7.   SVM (Non-linear algo)
8.   Bagged Decision Trees (Bagging)
9.   Random Forest (Bagging)
10.  Extra Trees (Bagging)
11.  AdaBoost (Boosting)
12.  Stochastic Gradient Boosting (Boosting)
13.  MLP (Deep Learning)
14.  XGBoost

"--------HERE I AM USING THE AUTO ENCODER MODEL FOR TRAING THE DATASET-------------"

In [238]:
"--------HERE I AM USING THE AUTO ENCODER MODEL FOR TRAING THE DATASET-------------"

'--------HERE I AM USING THE AUTO ENCODER MODEL FOR TRAING THE DATASET-------------'

In [239]:
cat_Featureslist = []
for colName,x in data_train.iloc[1,:].iteritems():
    if(str(x).isalpha()):
        cat_Featureslist.append(colName)
        
print(data_train[cat_Featureslist].apply(pd.Series.nunique))

cat1        2
cat2        2
cat3        2
cat4        2
cat5        2
         ... 
cat112     51
cat113     61
cat114     19
cat115     23
cat116    326
Length: 116, dtype: int64


In [240]:
from sklearn.preprocessing import LabelEncoder
for cf1 in cat_Featureslist:
    le = LabelEncoder()
    le.fit(data_train[cf1].unique())
    data_train[cf1] = le.transform(data_train[cf1])
    
print(data_train.head(5))

   id  cat1  cat2  cat3  cat4  cat5  cat6  cat7  cat8  cat9  ...     cont6  \
0   1     0     1     0     1     0     0     0     0     1  ...  0.718367   
1   2     0     1     0     0     0     0     0     0     1  ...  0.438917   
2   5     0     1     0     0     1     0     0     0     1  ...  0.289648   
3  10     1     1     0     1     0     0     0     0     1  ...  0.440945   
4  11     0     1     0     1     0     0     0     0     1  ...  0.178193   

      cont7    cont8    cont9   cont10    cont11    cont12    cont13  \
0  0.335060  0.30260  0.67135  0.83510  0.569745  0.594646  0.822493   
1  0.436585  0.60087  0.35127  0.43919  0.338312  0.366307  0.611431   
2  0.315545  0.27320  0.26076  0.32446  0.381398  0.373424  0.195709   
3  0.391128  0.31796  0.32128  0.44467  0.327915  0.321570  0.605077   
4  0.247408  0.24564  0.22089  0.21230  0.204687  0.202213  0.246011   

     cont14     loss  
0  0.714843  2213.18  
1  0.304496  1283.60  
2  0.774425  3005.09  
3  0.6

In [241]:
cont_Featureslist = []
for colName,x in data_train.iloc[1,:].iteritems():
    #print(x)
    if(not str(x).isalpha()):
        cont_Featureslist.append(colName)

print(cont_Featureslist)
cont_Featureslist.remove('id')

['id', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15', 'cat16', 'cat17', 'cat18', 'cat19', 'cat20', 'cat21', 'cat22', 'cat23', 'cat24', 'cat25', 'cat26', 'cat27', 'cat28', 'cat29', 'cat30', 'cat31', 'cat32', 'cat33', 'cat34', 'cat35', 'cat36', 'cat37', 'cat38', 'cat39', 'cat40', 'cat41', 'cat42', 'cat43', 'cat44', 'cat45', 'cat46', 'cat47', 'cat48', 'cat49', 'cat50', 'cat51', 'cat52', 'cat53', 'cat54', 'cat55', 'cat56', 'cat57', 'cat58', 'cat59', 'cat60', 'cat61', 'cat62', 'cat63', 'cat64', 'cat65', 'cat66', 'cat67', 'cat68', 'cat69', 'cat70', 'cat71', 'cat72', 'cat73', 'cat74', 'cat75', 'cat76', 'cat77', 'cat78', 'cat79', 'cat80', 'cat81', 'cat82', 'cat83', 'cat84', 'cat85', 'cat86', 'cat87', 'cat88', 'cat89', 'cat90', 'cat91', 'cat92', 'cat93', 'cat94', 'cat95', 'cat96', 'cat97', 'cat98', 'cat99', 'cat100', 'cat101', 'cat102', 'cat103', 'cat104', 'cat105', 'cat106', 'cat107', 'cat108', 'cat109', 'cat110', '

In [242]:
from __future__ import print_function
import keras
import os
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten, Input,UpSampling2D
#from keras.preprocessing.image import ImageDataGenerator
from keras.utils import to_categorical
from keras.models import Model
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
from keras import optimizers
from keras.layers import merge
#keras.layers.Concatenate
#from keras.layers import Concatenate
from keras.layers import Reshape
import numpy as np
import matplotlib.pyplot as plt

In [243]:
def encoder1(input_shape):
    x = Conv2D(16,(3,3), activation='relu', padding='same')(input_shape)
    x = MaxPooling2D((2,2), padding='same')(x)
    x = Conv2D(8,(3,3), activation='relu', padding='same')(x)
    x = MaxPooling2D((2,2), padding='same')(x)
    x = Conv2D(8,(3,3), activation='relu', padding='same')(x)
    encoded1 = MaxPooling2D((2,2), padding='same', name='encoder')(x)
    return encoded1
def decoder1(input_shape):
    encoded=encoder1(input_shape)
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(16, (3, 3), activation='relu',padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    decoded1 = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)
    return decoded1
print ('Starting auto1')
input_shape = Input(shape = [256,256,1])
model1 = Model(input_shape,decoder1(input_shape))
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print ('Starting autoencoder')
model1.summary()

Starting auto1
Starting autoencoder
Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         (None, 256, 256, 1)       0         
_________________________________________________________________
conv2d_50 (Conv2D)           (None, 256, 256, 16)      160       
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 128, 128, 16)      0         
_________________________________________________________________
conv2d_51 (Conv2D)           (None, 128, 128, 8)       1160      
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 64, 64, 8)         0         
_________________________________________________________________
conv2d_52 (Conv2D)           (None, 64, 64, 8)         584       
_________________________________________________________________
encoder (MaxPooling2D) 

In [244]:
model1.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [245]:
#X_train.reshape([-1,720, 1280,1]).
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error as MSE
from sklearn.model_selection import train_test_split
import cv2
import numpy as np

X = data_train[cont_Featureslist]
y = data_train.loss

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
X_train = np.resize(X_train,(256, 256))
X_train = X_train.reshape(1,256, 256, 1)
X_test = np.resize(X_test,(256, 256))
X_test = X_test.reshape(1,256, 256, 1)
y_train = np.resize(y_train,(256, 256))
y_train = y_train.reshape(1,256, 256, 1)
y_test = np.resize(y_test,(256, 256))
y_test = y_test.reshape(1,256, 256, 1)
print(y_train.shape)

(1, 256, 256, 1)


In [246]:
history = model1.fit(X_train, X_test)

Epoch 1/1
1/1 [==============================] - 1s 1s/step - loss: 125765.4141 - accuracy: 0.2436


In [247]:
history = model1.fit(y_train, y_test)

Epoch 1/1
1/1 [==============================] - 0s 119ms/step - loss: 17379850.0000 - accuracy: 0.0000e+00


In [248]:
history = model1.fit(X_train, y_train)

Epoch 1/1
1/1 [==============================] - 0s 159ms/step - loss: 17623198.0000 - accuracy: 0.0000e+00


In [249]:
y_pred = model1.predict(X_test)
print(y_pred)

[[[[6.7770183e-03]
   [1.8477440e-06]
   [4.7683716e-07]
   ...
   [2.5653839e-04]
   [5.8460236e-04]
   [9.9544418e-01]]

  [[8.6195588e-02]
   [1.2886852e-02]
   [1.9508600e-04]
   ...
   [1.0611415e-03]
   [5.9559345e-03]
   [9.7959018e-01]]

  [[4.0391535e-02]
   [1.4341569e-01]
   [2.3228228e-03]
   ...
   [1.9550323e-05]
   [8.4042549e-06]
   [7.8489268e-01]]

  ...

  [[1.0536152e-01]
   [2.1220386e-01]
   [3.3587128e-02]
   ...
   [9.3370676e-05]
   [2.3967057e-01]
   [8.6077785e-01]]

  [[4.7278950e-01]
   [6.2281787e-03]
   [2.0461380e-03]
   ...
   [5.0485134e-05]
   [9.2213899e-02]
   [9.5993662e-01]]

  [[1.9312328e-01]
   [1.7058426e-01]
   [6.3230723e-02]
   ...
   [3.8713217e-05]
   [6.6787899e-03]
   [7.7209961e-01]]]]


In [250]:
y_pred = model1.predict(X_test)
set2_list = list(y_pred)
print(list(set2_list[:10]))

[array([[[6.7770183e-03],
        [1.8477440e-06],
        [4.7683716e-07],
        ...,
        [2.5653839e-04],
        [5.8460236e-04],
        [9.9544418e-01]],

       [[8.6195588e-02],
        [1.2886852e-02],
        [1.9508600e-04],
        ...,
        [1.0611415e-03],
        [5.9559345e-03],
        [9.7959018e-01]],

       [[4.0391535e-02],
        [1.4341569e-01],
        [2.3228228e-03],
        ...,
        [1.9550323e-05],
        [8.4042549e-06],
        [7.8489268e-01]],

       ...,

       [[1.0536152e-01],
        [2.1220386e-01],
        [3.3587128e-02],
        ...,
        [9.3370676e-05],
        [2.3967057e-01],
        [8.6077785e-01]],

       [[4.7278950e-01],
        [6.2281787e-03],
        [2.0461380e-03],
        ...,
        [5.0485134e-05],
        [9.2213899e-02],
        [9.5993662e-01]],

       [[1.9312328e-01],
        [1.7058426e-01],
        [6.3230723e-02],
        ...,
        [3.8713217e-05],
        [6.6787899e-03],
        [7.7209961e-01]

In [252]:
import numpy
#predictions = numpy.expm1(model1.predict(X_test))
#del X_test
with open("result12.csv", "w") as subfile:
    subfile.write("id,loss\n")
    for i, pred in enumerate(list(set2_list)):
        subfile.write("%s,%s\n"%(ID[i],pred))

In [ ]:
import numpy
predictions = numpy.expm1(model1.predict(X_test))
del X_test
with open("result1.csv", "w") as subfile:
    subfile.write("id,loss\n")
    for i, pred in enumerate(list(predictions)):
        subfile.write("%s,%s\n"%(ID[i],pred))